const $=i=>document.getElementById(i),v=i=>parseFloat($(i).value),g=x=>+x.toPrecision(3),Z=376.73;
const lim=f=>f<400?2:f<2000?f/200:10;
let st={chk:[0,0,0,0,0],tech:0},cur;try{Object.assign(st,JSON.parse(localStorage.getItem('eb')||'{}'))}catch(e){}
const save=()=>{try{localStorage.setItem('eb',JSON.stringify({chk:st.chk,tech:st.tech}))}catch(e){}};
const MC={z:['#FACC15','<path d="M52 2 40 24h10l-6 16 18-22H52z" fill="#f59e0b"/>'],w:['#5EEAD4','<path d="M30 26q7-14 14 0t14 0t14 0" stroke="#0D9488" stroke-width=4 fill=none stroke-linecap=round />'],p:['#f9a8d4','<g fill="#f472b6"><circle cx=42 cy=27 r=7 /><circle cx=50 cy=22 r=8 /><circle cx=58 cy=27 r=7 /></g>'],b:['#7dd3fc','<path d="M50 3Q63 21 50 30Q37 21 50 3z" fill="#38bdf8"/>']};
function mas(k,mood){const [c,top]=MC[k],mo=mood=='w'?'M40 78 Q50 70 60 78':'M40 72 Q50 83 60 72';
return `<svg viewBox="0 0 100 100" width=84 class=bob aria-hidden=true>${top}<circle cx=50 cy=62 r=32 fill="${c}"/><circle cx=39 cy=58 r=5 fill="#1f2937"/><circle cx=61 cy=58 r=5 fill="#1f2937"/><circle cx=40.5 cy=56.5 r=1.6 fill="#fff"/><circle cx=62.5 cy=56.5 r=1.6 fill="#fff"/><path d="${mo}" stroke="#1f2937" stroke-width=3 fill=none stroke-linecap=round /><circle cx=31 cy=70 r=5 fill="#fb7185" opacity=.5/><circle cx=69 cy=70 r=5 fill="#fb7185" opacity=.5/></svg>`}
const say=(k,t,m)=>`<div class=say>${mas(k,m)}<div class=bub>${t}</div></div>`;
const NAV=[['home','Home','🏠'],['room','Room','🛋️'],['dist','Distance','↔️'],['habit','Habits','🌙'],['facts','Facts','📘']];
const ITEMS=['Wi-Fi router more than 2 m from where I sleep or work','Phone across the room at night or in airplane mode','Speaker or wired headset for long calls','Screens off 30 min before bed','Ethernet for stationary devices'];
const ckl=()=>ITEMS.map((t,i)=>`<label class=ck><input type=checkbox ${st.chk[i]?'checked':''} onchange="tg(${i})">${t}</label>`).join('');
function tg(i){st.chk[i]^=1;save();go(cur.id)}
function go(id){cur=S[id];cur.id=id;$('m').innerHTML=cur.h();$('hb').innerHTML=(st.tech?`<button onclick="go('tech')">🔬 Technical</button> `:'')+`<button onclick="go('set')">⚙️</button>`;$('nav').innerHTML=NAV.map(n=>`<button class="${n[0]==id?'on':''}" onclick="go('${n[0]}')"><i>${n[2]}</i>${n[1]}</button>`).join('');cur.c&&cur.c();scrollTo(0,0)}
const DEV=[['Wi-Fi router','📶',0.1,2400,1,3],['Smartphone','📱',0.2,1900,1,0.5],['Laptop','💻',0.05,2400,1,0.6],['Smart TV / IoT','📺',0.05,2400,1,2],['Bluetooth earbuds','🎧',0.0025,2400,0,0.05]];
const PR={'📱 Phone':[0.2,1900],'📶 Wi-Fi router':[0.1,2400],'🎧 Earbuds':[0.0025,2400]};
const S={};
S.set={h(){return `<h2>⚙️ Settings</h2>${say('w','Everything optional lives here.')}<div class=card><label class=ck><input type=checkbox ${st.tech?'checked':''} onchange="st.tech=this.checked?1:0;save();go('set')">🔬 Show the Technical space</label><p class=mut>Hidden by default. When on, a Technical button appears in the top bar. It is still under construction.</p></div><div class=card><label class=ck><input type=checkbox ${document.documentElement.dataset.theme=='dark'?'checked':''} onchange="document.documentElement.dataset.theme=this.checked?'dark':'light'">🌙 Dark theme</label></div>`}};
S.tech={h(){return `<h2>🔬 Technical space</h2>${say('z','Solvers, shielding and limits are coming soon!')}<button class=btn onclick="go('home')">← Back to Awareness</button>`}};
S.home={h(){const n=st.chk.filter(Boolean).length;return `${say('w',n>=3?'Nice habits! You are doing great.':'Hi! Try the Room Scanner to see what is around you.')}<div class=tiles>${[['room','🛋️','Room Scanner','Devices in your room'],['dist','↔️','Distance Fun','Slide away, see it drop'],['habit','🌙','Habit Tracker',n+' of 5 done today'],['facts','📘','Facts & Myths','Limits and honesty']].map(x=>`<button class="card tile" onclick="go('${x[0]}')"><i>${x[1]}</i><b>${x[2]}</b><div class=mut>${x[3]}</div></button>`).join('')}</div>`}};
S.room={h(){return `<h2>🛋️ Room Scanner</h2>${say('z','How many devices are in your room, and how far are they from you?')}<div class=card><div class=dev><b></b><small>How many</small><small>Meters</small></div>${DEV.map((d,i)=>`<div class=dev><span>${d[1]} ${d[0]}</span><input id=c${i} type=number min=0 step=1 value=${d[4]}><input id=d${i} type=number min=0.05 step=any value=${d[5]}></div>`).join('')}</div><div id=out></div>`},
c(){let tot=0,fr=0,n=0,g24=0,best=[0,''];DEV.forEach((d,i)=>{const c=Math.max(+$('c'+i).value||0,0),r=Math.max(+$('d'+i).value||0.05,0.05),s=c*d[2]/(4*Math.PI*r*r),f=s/lim(d[3]);tot+=s;fr+=f;n+=c;if(d[3]==2400)g24+=c;if(f>best[0])best=[f,d[0]]});
const E=Math.sqrt(tot*Z),p=fr*100,lv=p<1?['Very low','var(--ok)','Far below the guideline. Established science finds no health effect at levels like this.']:p<10?['Low','var(--ok)','Well inside the guideline. No established health effect.']:p<50?['Moderate','var(--warn)','Still inside the guideline, but you are using a fair share of the safety margin. Extra distance helps.']:p<100?['High','var(--warn)','Close to the guideline. Move devices farther away or switch some off.']:['Above guideline','var(--bad)','Over the guideline. Increase distance or reduce devices.'];
const crowd=g24>=6?'Crowded: expect Wi-Fi or Bluetooth slowdowns and dropouts.':g24>=3?'Busy: fine for most homes.':'Light: little chance of clashes.';
$('out').innerHTML=n?`${say('z',`Your room is <b>${lv[0]}</b>!${p>=10?' Let us fix that.':''}`,p>=10?'w':'h')}<div class=card><b>🩺 Health meter</b><div class=bar><i style="width:${Math.min(Math.max(p,2),100)}%;background:${lv[1]}"></i></div><p><b>${g(p)}%</b> of the ICNIRP public limit. ${lv[2]}</p><p class=mut>Worst case: every device transmitting at full power at once. Real use is far lower. This is not a medical diagnosis.</p></div><div class=card><b>📊 The numbers</b><table><tr><td>Devices<td>${n}<tr><td>Power density<td>${g(tot)} W/m²<tr><td>E-field (EMF)<td>${g(E)} V/m<tr><td>Biggest share<td>${best[1]} (${g(best[0]/fr*100)}%)</table></div><div class=card><b>📡 EMI</b> (devices disturbing each other)<br>${g24} devices share 2.4 GHz. ${crowd}</div><div class=card><b>✅ EMC</b> (living together peacefully)<br>Certified devices (CE, FCC, BIS) are built to coexist. Trouble mostly comes from cheap chargers, dimmers and damaged cables.<br><b>Tip:</b> doubling the distance to your ${best[1]} cuts its share to a quarter.</div>`:`${say('w','Add at least one device to scan.')}`}};
S.dist={h(){return `<h2>↔️ Distance Fun</h2>${say('b','Slide away from the device and watch the field shrink!')}<div class=card><div>${Object.keys(PR).map((k,i)=>`<label class=ck style="display:inline-flex;margin-right:10px"><input type=radio name=dv value="${k}" ${i?'':'checked'}>${k}</label>`).join('')}</div><b id=dl></b><input id=dd type=range min=0.1 max=5 step=0.05 value=1.5></div><div class=card id=out2></div>`},
c(){const [P,f]=PR[document.querySelector('[name=dv]:checked').value],d=v('dd'),s=x=>P/(4*Math.PI*x*x),rel=x=>(0.1/x)**2*100;$('dl').textContent=d.toFixed(2)+' m away';
$('out2').innerHTML=`<div class=bar><i style="width:${Math.max(rel(d),1.5)}%;background:var(--acc)"></i></div><p><b>${g(rel(d))}%</b> of the strength at 0.1 m<br>${g(s(d)/lim(f)*100)}% of the safety limit</p><table>${[0.1,0.5,1,2].map(x=>`<tr><td>${x} m<td>${g(rel(x))}%`).join('')}</table><p><b>Doubling distance = one quarter the power.</b></p><p class=mut>Free-space estimate at peak power. Very near an antenna the field is more complicated.</p>`}};
S.habit={h(){return `<h2>🌙 Habit Tracker</h2>${say('p','Tick what you did today!')}<div class=card>${ckl()}</div><div class=card><label class=ck><input type=checkbox ${document.documentElement.dataset.theme=='dark'?'checked':''} onchange="document.documentElement.dataset.theme=this.checked?'dark':'light'">🌙 Bedtime mode (dim theme)</label><p class=mut>Best-supported sleep habits: steady schedule, dark cool room, less screen light before bed.</p></div>`}};
const GL=[['EMF','Electromagnetic Field','Invisible energy fields around anything that uses electricity.'],['EMI','Electromagnetic Interference','Unwanted noise from one device that disturbs another.'],['EMC','Electromagnetic Compatibility','Devices working side by side without disturbing each other.'],['RF','Radio Frequency','Wireless signals used by Wi-Fi, phones and Bluetooth.'],['ELF','Extremely Low Frequency','Very slow fields, like the 50 Hz from mains power.'],['SAR','Specific Absorption Rate','How much phone energy the body absorbs, in W/kg.'],['ICNIRP','International Commission on Non-Ionizing Radiation Protection','Group that sets public exposure guidelines.'],['WHO','World Health Organization','The United Nations health agency.'],['IARC','International Agency for Research on Cancer','WHO body that classifies possible cancer risks.'],['FCC','Federal Communications Commission','US regulator for radio equipment.'],['CISPR','Comité International Spécial des Perturbations Radioélectriques','International committee behind emission limits for electronics.'],['CE','Conformité Européenne','Mark showing a product meets EU rules.'],['BIS','Bureau of Indian Standards','National standards body of India.'],['DoT','Department of Telecommunications','Indian government body that sets telecom EMF norms.'],['IoT','Internet of Things','Smart gadgets that connect online.'],['dBm','Decibel-milliwatt','Power level compared with 1 milliwatt.'],['dBµV/m','Decibel-microvolt per metre','Field level compared with 1 µV/m.'],['V/m','Volts per metre','Unit of electric field strength.'],['W/m²','Watts per square metre','Unit of power density.'],['Hz','Hertz','Cycles per second. kHz, MHz and GHz are thousands, millions and billions of Hz.']];
S.facts={h(){return `<h2>📘 Facts & Myths</h2>${say('b','Straight talk, no scare tactics.')}${[['SAR limits','US and India: 1.6 W/kg over 1 g of tissue. ICNIRP and EU: 2 W/kg over 10 g.'],['ICNIRP public limits','2 W/m² (10-400 MHz), f/200 W/m² (400-2000 MHz), 10 W/m² (2-300 GHz).'],['WHO','No health effects confirmed below guideline limits; research continues.'],['IARC','RF fields are Group 2B, "possibly carcinogenic", on limited evidence.'],['Myth: EMF stickers protect you','No credible evidence they work. Distance does.'],['Myth: headaches prove EMF harm','Blinded studies have not shown fields cause these symptoms. Talk to a doctor if they persist.']].map(x=>`<div class=card><b>${x[0]}</b><div class=mut>${x[1]}</div></div>`).join('')}<h2>🔤 Full forms</h2>${GL.map(x=>`<div class=card><b>${x[0]}</b> = ${x[1]}<div class=mut>${x[2]}</div></div>`).join('')}`}};
document.addEventListener('input',e=>{if(e.target.closest('#m')&&cur&&cur.c)cur.c()});
go('home');
