const $=i=>document.getElementById(i),v=i=>parseFloat($(i).value),g=x=>+x.toPrecision(4),lg=Math.log10,C=299792458,Z=376.73;
let st={mode:'a',chk:[0,0,0,0,0],hist:[]},cur,LB='',LS='u_v',S={};
try{Object.assign(st,JSON.parse(localStorage.getItem('emc')||'{}'))}catch(e){}
const save=()=>{try{localStorage.setItem('emc',JSON.stringify({chk:st.chk,hist:st.hist}))}catch(e){}};
const lim=f=>f<400?2:f<2000?f/200:10,dbuv=e=>20*lg(e*1e6);
const row=(id,l,val,u='')=>`<label>${l}<span><input id=${id} type=number step=any value=${val}>${u}</span></label>`;
const NAV={a:[['home','Home','◔'],['viz','Visualizer','↔'],['track','Tracker','✓'],['std','Standards','§']],t:[['work','Workspace','▦'],['rf','RF Field','📡'],['shield','Shielding','🛡'],['units','Units','⇄']]};
const ITEMS=['Wi-Fi router more than 2 m from where you sleep or work','Phone across the room at night (or in airplane mode)','Speaker or wired headset for calls over 30 min','Screens off 30 min before bed','Ethernet for stationary devices'];
const chkList=()=>ITEMS.map((t,i)=>`<label class=ck><input type=checkbox ${st.chk[i]?'checked':''} onchange="tg(${i})">${t}</label>`).join('');
function tg(i){st.chk[i]=st.chk[i]?0:1;save();go(st.scr)}
function night(b){document.documentElement.dataset.theme=b?'dark':'light'}
function setMode(m){st.mode=m;document.documentElement.dataset.mode=m;go(m=='a'?'home':'work')}
function go(id){st.scr=id;cur=S[id];$('m').innerHTML=cur.h();$('ma').className=st.mode=='a'?'on':'';$('mtb').className=st.mode=='t'?'on':'';$('logo').textContent=st.mode=='a'?'EMF Aware':'EMC Studio';
$('nav').innerHTML=NAV[st.mode].map(n=>`<button class="${n[0]==id?'on':''}" onclick="go('${n[0]}')"><span>${n[2]}</span>${n[1]}</button>`).join('');cur.c&&cur.c();scrollTo(0,0)}
function sv(type,ids){st.hist.unshift({s:type,t:LB,v:Object.fromEntries(ids.map(i=>[i,$(i).value]))});st.hist=st.hist.slice(0,5);save();event.target.textContent='Saved ✓'}
function ld(i){const h=st.hist[i];go(h.s);for(const k in h.v)$(k).value=h.v[k];cur.c()}
const PR={'Smartphone':[0.2,1900],'Wi-Fi router':[0.1,2400],'Bluetooth earbuds':[0.0025,2400]};
S.home={h(){const n=st.chk.filter(Boolean).length,p=n*20,c=p>=70?'ok':p>=40?'warn':'bad',r=45,L=2*Math.PI*r,col=p>=70?'var(--ok)':p>=40?'var(--warn)':'var(--bad)';
return `<h2>Daily habit dashboard</h2><div class="card c"><svg viewBox="0 0 120 120" width=170><circle cx=60 cy=60 r=${r} fill=none stroke="var(--line)" stroke-width=10 /><circle cx=60 cy=60 r=${r} fill=none stroke="${col}" stroke-width=10 stroke-linecap=round stroke-dasharray="${L*p/100} ${L}" transform="rotate(-90 60 60)"/><text x=60 y=66 text-anchor=middle class=big>${p}%</text></svg><div>${n} of 5 low-exposure habits done</div></div>
<div class=card><b>💡 Tip of the day</b><br>Moving a phone from 10 cm to 1 m cuts far-field power density by 99% (100×). Distance is the cheapest lever you have.<br><button onclick="go('viz')">Try the visualizer →</button></div>
<div class=card><b>Checklist</b>${chkList()}</div><p class=mut>Everyday devices sit far below international limits. These habits are precautionary, not a treatment.</p>`}};
S.viz={h(){return `<h2>Distance visualizer</h2><div class=card><div class=seg>${Object.keys(PR).map((k,i)=>`<label><input type=radio name=dv value="${k}" ${i?'':'checked'}>${k}</label>`).join('')}</div><label>Distance <b id=dl></b></label><input id=dd type=range min=0.1 max=5 step=0.05 value=1.5></div><div class=card id=out></div>`},
c(){const [P,f]=PR[document.querySelector('[name=dv]:checked').value],d=v('dd'),s=x=>P/(4*Math.PI*x*x),rel=x=>(0.1/x)**2*100;$('dl').textContent=d.toFixed(2)+' m';
$('out').innerHTML=`<div class=bar><i style="width:${Math.max(rel(d),1)}%"></i></div><p><b class=mono>${g(rel(d))}%</b> of the intensity at 0.1 m</p><p>Power density <b class=mono>${g(s(d))} W/m²</b> = <b class=mono>${g(s(d)/lim(f)*100)}%</b> of the ICNIRP public limit</p><table>${[0.1,0.5,1,2].map(x=>`<tr><td>${x} m<td class=mono>${g(rel(x))}%<td>−${g(100-rel(x))}%`).join('')}</table><p><b>Takeaway:</b> doubling distance quarters the power density.</p><p class=mut>Free-space far-field estimate at the device's peak transmit power (real use is usually lower). Very close to an antenna the field behaves less simply.</p>`}};
S.track={h(){return `<h2>Sleep & habit tracker</h2><div class=card>${chkList()}</div><div class=card><label class=ck><input type=checkbox ${document.documentElement.dataset.theme=='dark'?'checked':''} onchange="night(this.checked)">🌙 Bedtime mode (dim theme)</label><p class=mut>Best-supported sleep habits: a steady schedule, a dark cool room and less screen light before bed. No established link exists between everyday device fields and poor sleep, but a phone away from the pillow costs nothing.</p></div>`}};
S.std={h(){return `<h2>Standards explorer</h2>${[['SAR limits','US (FCC) and India (DoT): 1.6 W/kg averaged over 1 g of tissue. ICNIRP and EU: 2 W/kg over 10 g.'],['ICNIRP 2020 public reference levels','Power density 2 W/m² (10–400 MHz), f/200 W/m² (400–2000 MHz), 10 W/m² (2–300 GHz).'],['WHO position','Studies so far have not confirmed health effects from exposure below guideline limits; research continues.'],['IARC classification','RF fields are Group 2B, "possibly carcinogenic", based on limited evidence (2011).']].map(x=>`<div class=card><b>${x[0]}</b><p>${x[1]}</p></div>`).join('')}`}};
S.work={h(){return `<h2>Solver hub</h2><div class=grid>${[['rf','📡 RF Field & Power','E, S, region'],['shield','🛡 Shielding','SE, skin depth'],['units','📊 Unit matrix','dBm, dBµV/m, V/m, W/m²'],['lim','📋 Limits','CISPR 32, FCC 15']].map(x=>`<button class="card sc" onclick="go('${x[0]}')"><b>${x[1]}</b><br><small>${x[2]}</small></button>`).join('')}</div><h3>Recent calculations</h3>${st.hist.length?st.hist.map((h,i)=>`<button class="card sc" onclick="ld(${i})">${h.t}</button>`).join(''):'<p class=mut>Save a result to see it here.</p>'}`}};
S.rf={h(){return `<h2>RF field & power density</h2><div class=card>${row('rp','Transmit power',2,'<select id=rpu><option>W<option>dBm</select>')}${row('rg','Antenna gain',3,'dBi')}${row('rd','Distance',1,'<select id=rdu><option>m<option>ft</select>')}${row('rf','Frequency',2400,'MHz')}</div><div class=card id=out></div>`},
c(){let P=v('rp');if($('rpu').value=='dBm')P=1e-3*10**(P/10);const G=10**(v('rg')/10),d=v('rd')*($('rdu').value=='ft'?.3048:1),f=v('rf');
if(!(P>0&&d>0&&f>0)){$('out').textContent='Enter positive values';return}
const s=P*G/(4*Math.PI*d*d),E=Math.sqrt(s*Z),lam=C/(f*1e6),nf=lam/(2*Math.PI),El=Math.sqrt(lim(f)*Z),m=20*lg(El/E);
LB=`${f} MHz · ${v('rp')} ${$('rpu').value} · d=${v('rd')} ${$('rdu').value} → E=${g(E)} V/m`;
$('out').innerHTML=`<table><tr><td>Electric field<td class=mono>${g(E)} V/m<tr><td>Field level<td class=mono>${g(dbuv(E))} dBµV/m<tr><td>Power density<td class=mono>${g(s)} W/m²<tr><td>Wavelength<td class=mono>${g(lam)} m<tr><td>Reactive boundary λ/2π<td class=mono>${g(nf)} m</table><p><b>Region:</b> ${d<nf?'<span class=bad>REACTIVE NEAR-FIELD, formulas not valid</span>':'<span class=ok>RADIATING / FAR-FIELD</span>'}</p><p><b>ICNIRP public limit:</b> <span class=mono>${g(El)} V/m</span><br><b>Margin:</b> <b class=${m>=0?'ok':'bad'}>${g(Math.abs(m))} dB ${m>=0?'below':'ABOVE'} the limit</b></p><p class=mut>For large antennas also check d &gt; 2D²/λ (Fraunhofer distance).</p><button onclick="sv('rf',['rp','rpu','rg','rd','rdu','rf'])">Save to recent</button>`}};
const MT={Copper:[1,1],Aluminium:[.61,1],Steel:[.1,200],Brass:[.28,1],'Mu-metal':[.03,20000]};
S.shield={h(){return `<h2>Shielding & skin depth</h2><div class=card><label>Material<select id=mt>${Object.keys(MT).map(k=>`<option>${k}`).join('')}</select></label>${row('sr','σ vs copper',1)}${row('mr','μr',1)}${row('st','Thickness',0.5,'mm')}${row('sf','Frequency',100,'MHz')}<div class=mut>Edit σ and μr for a custom material.</div></div><div class=card id=out></div>`},
c(e){if(e&&e.target.id=='mt'){const q=MT[$('mt').value];$('sr').value=q[0];$('mr').value=q[1]}
const sr=v('sr'),mr=v('mr'),t=v('st')/1e3,f=v('sf')*1e6;if(!(sr>0&&mr>0&&t>0&&f>0)){$('out').textContent='Enter positive values';return}
const dl=1/Math.sqrt(Math.PI*f*4e-7*Math.PI*mr*5.8e7*sr),A=8.686*t/dl,R=168+10*lg(sr/(mr*f)),B=A<10?20*lg(Math.max(Math.abs(1-Math.exp(-2*t/dl)),1e-9)):0,T=Math.max(A+R+B,0);
LB=`${$('mt').value} ${v('st')} mm @ ${v('sf')} MHz → SE ${g(T)} dB`;
$('out').innerHTML=`<table><tr><td>Skin depth δ<td class=mono>${g(dl*1e6)} µm<tr><td>Absorption A<td class=mono>${g(A)} dB<tr><td>Reflection R<td class=mono>${g(R)} dB<tr><td>Multiple refl. B<td class=mono>${g(B)} dB<tr><td><b>Total SE</b><td class=mono><b>${g(T)} dB</b></table><p>Transmitted field: <span class=mono>${(10**(-T/20)*100).toExponential(1)}%</span>${t<dl?'<br><span class=bad>t &lt; δ: thin-film regime, the model is approximate.</span>':''}</p><p class=mut>Plane-wave model. Real enclosures are limited by seams and holes (often ~60–100 dB), and low-frequency magnetic fields are shielded far less.</p><button onclick="sv('shield',['mt','sr','mr','st','sf'])">Save to recent</button>`}};
S.units={h(){return `<h2>Spectrum unit matrix</h2><div class=card>${row('uf','Frequency',2400,'MHz')}${row('u_v','E-field',1,'V/m')}${row('u_dbuv','Level',120,'dBµV/m')}${row('u_s','Power density',0.00265,'W/m²')}${row('u_dbm','Isotropic rx power',0,'dBm')}</div><p class=mut>Edit any field and the others update. dBm is the power received by an ideal isotropic antenna at that frequency.</p>`},
c(e){const src=e&&e.target.id.startsWith('u_')?e.target.id:LS;LS=src;const x=v(src),lam=C/(v('uf')*1e6);if(!(v('uf')>0)||isNaN(x))return;
const s=src=='u_s'?x:src=='u_v'?x*x/Z:src=='u_dbuv'?(1e-6*10**(x/20))**2/Z:1e-3*10**(x/10)*4*Math.PI/(lam*lam),E=Math.sqrt(s*Z),o={u_v:E,u_dbuv:dbuv(E),u_s:s,u_dbm:10*lg(s*lam*lam/(4*Math.PI)/1e-3)};
for(const k in o)if(k!=src)$(k).value=g(o[k])}};
const LM=[['CISPR 32 Class B',10,[[30,30],[230,30],[230,37],[1000,37]]],['CISPR 32 Class A',10,[[30,40],[230,40],[230,47],[1000,47]]],['FCC 15 Class B',3,[[30,40],[88,40],[88,43.5],[216,43.5],[216,46],[960,46],[960,54],[1000,54]]]];
S.lim={h(){return `<button class=back onclick="go('work')">← Workspace</button><h2>EMC limits & compliance</h2><div class=card><label>Standard<select id=ls>${LM.map((x,i)=>`<option value=${i}>${x[0]}`).join('')}</select></label>${row('lf','Frequency',100,'MHz')}${row('ll','Your level',28,'dBµV/m')}${row('ld','Measure distance',10,'m')}</div><div class=card id=out></div>`},
c(){const [nm,rd,pts]=LM[+$('ls').value],f=Math.min(Math.max(v('lf'),30.001),1000),d=v('ld'),L=v('ll');if(!(d>0)||isNaN(L)){$('out').textContent='Enter valid values';return}
const sc=20*lg(rd/d),lm=pts.filter(p=>p[0]<f).pop()[1]+sc,m=lm-L,X=q=>10+(lg(q)-lg(30))/(lg(1000)-lg(30))*280,Y=q=>130-(q-20)/40*120;
$('out').innerHTML=`<svg viewBox="0 0 300 140" width=100%><polyline fill=none stroke="var(--acc)" stroke-width=2 points="${pts.map(p=>X(p[0])+','+Y(Math.min(p[1]+sc,60))).join(' ')}"/><circle cx=${X(f)} cy=${Y(Math.min(Math.max(L,20),60))} r=5 fill="${m>=0?'var(--ok)':'var(--bad)'}"/><text x=10 y=12 font-size=9 fill="var(--mut)">dBµV/m, 30 MHz–1 GHz</text></svg><p>Limit at ${g(f)} MHz, ${d} m: <b class=mono>${g(lm)} dBµV/m</b> (scaled 20·log(d₀/d) from ${rd} m)</p><p><b class=${m>=0?'ok':'bad'}>${m>=0?'PASS':'FAIL'}: margin ${g(m)} dB</b></p><p class=mut>Aim for 6 dB or more in pre-compliance. Quasi-peak limits, screening only.</p>`}};
document.addEventListener('input',e=>{if(e.target.closest('#m')&&cur&&cur.c)cur.c(e)});
setMode(st.mode);
